default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  sslmode: require

development:
  <<: *default
  database: db/development.sqlite3
  adapter: sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  adapter: sqlite3

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] %>
